source 'https://rubygems.org'

gem 'sinatra', '~> 2.1'
gem 'webrick', '~> 1.7'
gem 'json', '~> 2.5'
gem 'securerandom', '~> 0.1'
gem 'sys-proctable', '~> 1.2'
gem 'seccomp-tools', '~> 1.1' # Assuming a Ruby seccomp library exists